name: php
toolstack: "php:symfony"

web:
    # index_files:
    #   - "index.html"
    #   - "index.htm"
    passthru: "/test.php"
    whitelist:
      - "\\.html?$"
      - "\\.htm?$"
      - "\\.txt?$"
    document_root: "/www"

disk: 2048
